### PR TITLE
[WIP] implement  skeleton

### PR DESCRIPTION
**Pull request by tdtds**

### CODE REVIEW

**Comment by tdtds** [comment]
I have known RSpec is not good choice with fluentd. I will try to make another branch made by `fluent-plugin-generate` command.

**Comment by cosmo0920** [comment]
We can work with either rspec or test-unit. 
We can review or make an advice in both cases.

**Comment by tdtds** [comment]
Thank you @cosmo0920, I do not mean have a doubt on the ability of you. 
But this is a first plugin on me, I want to code this based on the standard style of fluentd.

**Comment by cosmo0920** [comment]
Yep, no problem. 
Following standard style sounds reasonable for me.

**Pull request closed without merging**
